# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: dockboxhq
      name: cli

    # Template for the url which is determined by the given Token (github or gitlab)
    # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_template: "https://github.com/dockbox/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: sriharivishnu
      email: srihari.vishnu@gmail.com

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: "Create a new dockbox by running `dockbox create <url>` command."

    # Your app's homepage.
    # Default is empty.
    # homepage: ""

    # Your app's description.
    # Default is empty.
    description: "`dockbox` is a useful CLI tool for trying out code from remote repositories. It allows you to to try out code quickly and easily without compromising your own system"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"

    # Packages your package depends on.
    dependencies:
      - name: git
      - name: go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
