# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "`dockbox` is a useful CLI tool for trying out code from remote repositories. It allows you to to try out code quickly and easily without compromising your own system"
  homepage ""
  version "0.0.3-patch"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dockbox/cli/releases/download/v0.0.3-patch/cli_0.0.3-patch_Darwin_x86_64.tar.gz"
      sha256 "b5b149a64bbc1d68e522262b210b6b9e530b27cfbbc59a07ee52dee4e96d5777"
    end
    if Hardware::CPU.arm?
      url "https://github.com/dockbox/cli/releases/download/v0.0.3-patch/cli_0.0.3-patch_Darwin_arm64.tar.gz"
      sha256 "d19860a84b8943bb5a5b81493aba9ca4c5dee7cc5eeed1fff234bb5389d90ad7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dockbox/cli/releases/download/v0.0.3-patch/cli_0.0.3-patch_Linux_x86_64.tar.gz"
      sha256 "89d2379a01de0b8da5dfaba0cace2907a464ea830a047f5d65c2138d9525dfd5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dockbox/cli/releases/download/v0.0.3-patch/cli_0.0.3-patch_Linux_arm64.tar.gz"
      sha256 "130bcb630c9270c830db359d4e62c5891a9323d82dc764c07a51c5ae1638eb5d"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "cli"
  end

  def caveats; <<~EOS
    Create a new dockbox by running `dockbox create <url>` command.
  EOS
  end
end
