package cmd

import (
	"fmt"
)

var IgnoredFilesForAnalysis = []string{".git/*"}

type Image struct {
	Image string
	Dependencies []string
	Commands []string
	EntryPoint string
}

// type Command struct {

// }

func (i Image) String() string {
	return fmt.Sprintf("{'image': %s, 'dependencies': %s, 'commands': %s}", i.Image, i.Dependencies, i.Commands)
}

var LanguageToImageMapper = map[string]Image {
	"python": {
		"python:3.8-slim-buster",
		[]string{"requirements.txt"},
		[]string{"pip install -r requirements.txt"},
		"/bin/sh",
	},
	"javascript": {
		"node:14",
		[]string{"package.json"},
		[]string{"npm install"},
		"/bin/sh",
	},
	"unknown": {
		"ubuntu:18.04",
		[]string{},
		[]string{},
		"/bin/sh",
	},
}

// https://github.com/jonschlinkert/lang-map/blob/master/lib/exts.json
var ExtensionToLanguage = map[string]string {
	".1": "groff",
	".2": "groff",
	".3": "groff",
	".4": "groff",
	".4th": "forth",
	".5": "groff",
	".6": "groff",
	".6pl": "perl6",
	".6pm": "perl6",
	".7": "groff",
	".E": "e",
	".ML": "standard ml",
	"._coffee": "coffeescript",
	"._js": "javascript",
	"._ls": "livescript",
	".a51": "assembly",
	".abap": "abap",
	".ada": "ada",
	".adb": "ada",
	".ado": "stata",
	".adoc": "asciidoc",
	".adp": "tcl",
	".ads": "ada",
	".agda": "agda",
	".ahk": "autohotkey",
	".ahkl": "autohotkey",
	".aj": "aspectj",
	".als": "alloy",
	".ampl": "ampl",
	".ant": "xml",
	".apacheconf": "apacheconf",
	".apl": "apl",
	".applescript": "applescript",
	".arc": "arc",
	".as": "actionscript",
	".asax": "asp",
	".asc": "ags script",
	".asciidoc": "asciidoc",
	".ascx": "asp",
	".asd": "common lisp",
	".ash": "ags script",
	".ashx": "asp",
	".asm": "assembly",
	".asmx": "asp",
	".asp": "asp",
	".aspx": "asp",
	".au3": "autoit",
	".aug": "augeas",
	".auk": "awk",
	".aux": "tex",
	".aw": "php",
	".awk": "awk",
	".axd": "asp",
	".axi": "netlinx",
	".axi.erb": "netlinx+erb",
	".axml": "xml",
	".axs": "netlinx",
	".axs.erb": "netlinx+erb",
	".b": "brainfuck",
	".bas": "visual basic",
	".bash": "shell",
	".bat": "batchfile",
	".bats": "shell",
	".bb": "bitbake",
	".bbx": "tex",
	".befunge": "befunge",
	".bf": "brainfuck",
	".bib": "tex",
	".bmx": "blitzmax",
	".bones": "javascript",
	".boo": "boo",
	".boot": "clojure",
	".brd": "eagle",
	".bro": "bro",
	".brs": "brightscript",
	".bsv": "bluespec",
	".builder": "ruby",
	".c": "c",
	".c++": "c++",
	".c++-objdump": "cpp-objdump",
	".c++objdump": "cpp-objdump",
	".c-objdump": "c-objdump",
	".capnp": "cap'n proto",
	".cats": "c",
	".cbl": "cobol",
	".cbx": "tex",
	".cc": "c++",
	".ccp": "cobol",
	".ccxml": "xml",
	".cdf": "mathematica",
	".ceylon": "ceylon",
	".cfc": "coldfusion cfc",
	".cfg": "ini",
	".cfm": "coldfusion",
	".cfml": "coldfusion",
	".cgi": "perl",
	".chpl": "chapel",
	".chs": "c2hs haskell",
	".cirru": "cirru",
	".cjsx": "coffeescript",
	".ck": "chuck",
	".cl": "common lisp",
	".cl2": "clojure",
	".clixml": "xml",
	".clj": "clojure",
	".cljc": "clojure",
	".cljs": "clojure",
	".cljs.hl": "clojure",
	".cljscm": "clojure",
	".cljx": "clojure",
	".clp": "clips",
	".cls": "apex",
	".clw": "clarion",
	".cmake": "cmake",
	".cmake.in": "cmake",
	".cmd": "batchfile",
	".cob": "cobol",
	".cobol": "cobol",
	".coffee": "coffeescript",
	".com": "digital command language",
	".command": "shell",
	".coq": "coq",
	".cp": "c++",
	".cpp": "c++",
	".cpp-objdump": "cpp-objdump",
	".cppobjdump": "cpp-objdump",
	".cproject": "xml",
	".cps": "component pascal",
	".cpy": "cobol",
	".cql": "sql",
	".cr": "crystal",
	".creole": "creole",
	".cs": "c#",
	".csh": "tcsh",
	".cshtml": "c#",
	".cson": "coffeescript",
	".csproj": "xml",
	".css": "css",
	".csx": "c#",
	".ct": "xml",
	".ctp": "php",
	".cu": "cuda",
	".cuh": "cuda",
	".cw": "redcode",
	".cxx": "c++",
	".cxx-objdump": "cpp-objdump",
	".cy": "cycript",
	".d": "d",
	".d-objdump": "d-objdump",
	".darcspatch": "darcs patch",
	".dart": "dart",
	".dats": "ats",
	".db2": "sqlpl",
	".dcl": "clean",
	".ddl": "sql",
	".decls": "blitzbasic",
	".desktop": "desktop",
	".desktop.in": "desktop",
	".dfm": "pascal",
	".di": "d",
	".diff": "diff",
	".dita": "xml",
	".ditamap": "xml",
	".ditaval": "xml",
	".djs": "dogescript",
	".dll.config": "xml",
	".dlm": "idl",
	".dm": "dm",
	".do": "stata",
	".dockerfile": "dockerfile",
	".doh": "stata",
	".dot": "graphviz (dot)",
	".dpatch": "darcs patch",
	".dpr": "pascal",
	".druby": "mirah",
	".dtx": "tex",
	".duby": "mirah",
	".dyalog": "apl",
	".dyl": "dylan",
	".dylan": "dylan",
	".e": "eiffel",
	".ebuild": "gentoo ebuild",
	".ec": "ec",
	".ecl": "ecl",
	".eclass": "gentoo eclass",
	".eclxml": "ecl",
	".edn": "edn",
	".eh": "ec",
	".el": "emacs lisp",
	".eliom": "ocaml",
	".eliomi": "ocaml",
	".elm": "elm",
	".em": "emberscript",
	".emacs": "emacs lisp",
	".emacs.desktop": "emacs lisp",
	".emberscript": "emberscript",
	".epj": "ecere projects",
	".eps": "postscript",
	".erb": "html+erb",
	".erb.deface": "html+erb",
	".erl": "erlang",
	".es": "erlang",
	".es6": "javascript",
	".escript": "erlang",
	".ex": "elixir",
	".exs": "elixir",
	".f": "fortran",
	".f03": "fortran",
	".f08": "fortran",
	".f77": "fortran",
	".f90": "fortran",
	".f95": "fortran",
	".factor": "factor",
	".fan": "fantom",
	".fancypack": "fancy",
	".fcgi": "lua",
	".feature": "cucumber",
	".filters": "xml",
	".fish": "fish",
	".flex": "jflex",
	".flux": "flux",
	".for": "fortran",
	".forth": "forth",
	".fp": "glsl",
	".fpp": "fortran",
	".fr": "forth",
	".frag": "glsl",
	".frg": "glsl",
	".frm": "visual basic",
	".frt": "forth",
	".frx": "visual basic",
	".fs": "f#",
	".fshader": "glsl",
	".fsi": "f#",
	".fsproj": "xml",
	".fsx": "f#",
	".fth": "forth",
	".fun": "standard ml",
	".fx": "flux",
	".fxml": "xml",
	".fy": "fancy",
	".g": "g-code",
	".g4": "antlr",
	".gap": "gap",
	".gawk": "awk",
	".gco": "g-code",
	".gcode": "g-code",
	".gd": "gap",
	".gemspec": "ruby",
	".geo": "glsl",
	".geom": "glsl",
	".gf": "grammatical framework",
	".gi": "gap",
	".glade": "xml",
	".glf": "glyph",
	".glsl": "glsl",
	".glslv": "glsl",
	".gml": "game maker language",
	".gms": "gams",
	".gnu": "gnuplot",
	".gnuplot": "gnuplot",
	".go": "go",
	".god": "ruby",
	".golo": "golo",
	".gp": "gnuplot",
	".grace": "grace",
	".gradle": "gradle",
	".groovy": "groovy",
	".grt": "groovy",
	".grxml": "xml",
	".gs": "gosu",
	".gshader": "glsl",
	".gsp": "groovy server pages",
	".gst": "gosu",
	".gsx": "gosu",
	".gtpl": "groovy",
	".gv": "graphviz (dot)",
	".gvy": "groovy",
	".gyp": "python",
	".h": "c",
	".h++": "c++",
	".haml": "haml",
	".haml.deface": "haml",
	".handlebars": "handlebars",
	".hats": "ats",
	".hb": "harbour",
	".hbs": "handlebars",
	".hh": "c++",
	".hic": "clojure",
	".hlean": "lean",
	".hpp": "c++",
	".hqf": "sqf",
	".hrl": "erlang",
	".hs": "haskell",
	".hsc": "haskell",
	".htm": "html",
	".html": "html",
	".html.hl": "html",
	".http": "http",
	".hx": "haxe",
	".hxsl": "haxe",
	".hxx": "c++",
	".hy": "hy",
	".i7x": "inform 7",
	".iced": "coffeescript",
	".icl": "clean",
	".idc": "c",
	".idr": "idris",
	".ihlp": "stata",
	".ijs": "j",
	".ik": "ioke",
	".ily": "lilypond",
	".ini": "ini",
	".inl": "c++",
	".ino": "arduino",
	".ins": "tex",
	".intr": "dylan",
	".io": "io",
	".ipf": "igor pro",
	".ipp": "c++",
	".irbrc": "ruby",
	".irclog": "irc log",
	".iss": "inno setup",
	".ivy": "xml",
	".j": "jasmin",
	".jade": "jade",
	".jake": "javascript",
	".java": "java",
	".jbuilder": "ruby",
	".jelly": "xml",
	".jflex": "jflex",
	".jinja": "html+django",
	".jl": "julia",
	".jq": "jsoniq",
	".js": "javascript",
	".jsb": "javascript",
	".jsfl": "javascript",
	".jsm": "javascript",
	".json": "json",
	".json5": "json5",
	".jsonld": "jsonld",
	".jsp": "java server pages",
	".jss": "javascript",
	".jsx": "javascript",
	".kid": "genshi",
	".kit": "kit",
	".kml": "xml",
	".krl": "krl",
	".ksh": "shell",
	".kt": "kotlin",
	".ktm": "kotlin",
	".kts": "kotlin",
	".lagda": "literate agda",
	".las": "lasso",
	".lasso": "lasso",
	".lasso8": "lasso",
	".lasso9": "lasso",
	".latte": "latte",
	".launch": "xml",
	".lbx": "tex",
	".ld": "linker script",
	".ldml": "lasso",
	".lds": "linker script",
	".lean": "lean",
	".less": "less",
	".lfe": "lfe",
	".lgt": "logtalk",
	".lhs": "literate haskell",
	".lid": "dylan",
	".lidr": "idris",
	".liquid": "liquid",
	".lisp": "common lisp",
	".litcoffee": "literate coffeescript",
	".ll": "llvm",
	".lmi": "python",
	".lock": "json",
	".logtalk": "logtalk",
	".lol": "lolcode",
	".lookml": "lookml",
	".lpr": "pascal",
	".ls": "livescript",
	".lsl": "lsl",
	".lsp": "common lisp",
	".ltx": "tex",
	".lua": "lua",
	".lvproj": "labview",
	".ly": "lilypond",
	".m": "limbo",
	".ma": "mathematica",
	".mak": "makefile",
	".mako": "mako",
	".man": "groff",
	".mao": "mako",
	".markdown": "markdown",
	".mask": "mask",
	".mata": "stata",
	".matah": "stata",
	".mathematica": "mathematica",
	".matlab": "matlab",
	".mawk": "awk",
	".maxhelp": "max",
	".maxpat": "max",
	".maxproj": "max",
	".md": "markdown",
	".mediawiki": "mediawiki",
	".minid": "minid",
	".mir": "mirah",
	".mirah": "mirah",
	".mk": "makefile",
	".mkd": "markdown",
	".mkdn": "markdown",
	".mkdown": "markdown",
	".mkii": "tex",
	".mkiv": "tex",
	".mkvi": "tex",
	".ml": "ocaml",
	".ml4": "ocaml",
	".mli": "ocaml",
	".mll": "ocaml",
	".mly": "ocaml",
	".mm": "objective-c++",
	".mmk": "module management system",
	".mms": "module management system",
	".mo": "modelica",
	".monkey": "monkey",
	".moo": "mercury",
	".moon": "moonscript",
	".mspec": "ruby",
	".mss": "cartocss",
	".mtml": "mtml",
	".mu": "mupad",
	".muf": "muf",
	".mumps": "m",
	".mustache": "html+django",
	".mxml": "xml",
	".mxt": "max",
	".myt": "myghty",
	".n": "nemerle",
	".nasm": "assembly",
	".nawk": "awk",
	".nb": "mathematica",
	".nbp": "mathematica",
	".nc": "nesc",
	".nginxconf": "nginx",
	".ni": "inform 7",
	".nim": "nimrod",
	".nimrod": "nimrod",
	".ninja": "ninja",
	".nit": "nit",
	".nix": "nix",
	".njs": "javascript",
	".nl": "nl",
	".nlogo": "netlogo",
	".nproj": "xml",
	".nqp": "perl6",
	".nse": "lua",
	".nsh": "nsis",
	".nsi": "nsis",
	".nu": "nu",
	".numpy": "numpy",
	".numpyw": "numpy",
	".numsc": "numpy",
	".nuspec": "xml",
	".nut": "squirrel",
	".ny": "common lisp",
	".objdump": "objdump",
	".odd": "xml",
	".omgrofl": "omgrofl",
	".ooc": "ooc",
	".opa": "opa",
	".opal": "opal",
	".opencl": "opencl",
	".org": "org",
	".osm": "xml",
	".owl": "web ontology language",
	".ox": "ox",
	".oxh": "ox",
	".oxo": "ox",
	".oxygene": "oxygene",
	".oz": "oz",
	".p": "openedge abl",
	".p6": "perl6",
	".p6l": "perl6",
	".p6m": "perl6",
	".pac": "javascript",
	".pan": "pan",
	".parrot": "parrot",
	".pas": "pascal",
	".pasm": "parrot assembly",
	".pat": "max",
	".patch": "diff",
	".pb": "purebasic",
	".pbi": "purebasic",
	".pd": "pure data",
	".pd_lua": "lua",
	".pde": "processing",
	".perl": "perl",
	".ph": "perl",
	".php": "hack",
	".php3": "php",
	".php4": "php",
	".php5": "php",
	".phpt": "php",
	".phtml": "html+php",
	".pig": "piglatin",
	".pike": "pike",
	".pir": "parrot internal representation",
	".pkb": "plsql",
	".pks": "plsql",
	".pl": "perl",
	".pl6": "perl6",
	".plb": "plsql",
	".plist": "xml",
	".plot": "gnuplot",
	".pls": "plsql",
	".plsql": "plsql",
	".plt": "gnuplot",
	".pluginspec": "ruby",
	".plx": "perl",
	".pm": "perl",
	".pm6": "perl6",
	".pmod": "pike",
	".po": "gettext catalog",
	".pod": "perl",
	".podsl": "common lisp",
	".podspec": "ruby",
	".pogo": "pogoscript",
	".pot": "gettext catalog",
	".pp": "pascal",
	".prc": "sql",
	".prefs": "ini",
	".prg": "xbase",
	".pri": "qmake",
	".pro": "idl",
	".prolog": "prolog",
	".properties": "ini",
	".proto": "protocol buffer",
	".ps": "postscript",
	".ps1": "powershell",
	".ps1xml": "xml",
	".psc": "papyrus",
	".psc1": "xml",
	".psd1": "powershell",
	".psgi": "perl",
	".psm1": "powershell",
	".pt": "xml",
	".pub": "public key",
	".purs": "purescript",
	".pwn": "pawn",
	".pxd": "cython",
	".pxi": "cython",
	".py": "python",
	".pyde": "python",
	".pyp": "python",
	".pyt": "python",
	".pytb": "python traceback",
	".pyw": "python",
	".pyx": "cython",
	".qml": "qml",
	".r": "r",
	".r2": "rebol",
	".r3": "rebol",
	".rabl": "ruby",
	".rake": "ruby",
	".raml": "raml",
	".raw": "raw token data",
	".rb": "ruby",
	".rbbas": "realbasic",
	".rbfrm": "realbasic",
	".rbmnu": "realbasic",
	".rbres": "realbasic",
	".rbtbar": "realbasic",
	".rbuild": "ruby",
	".rbuistate": "realbasic",
	".rbw": "ruby",
	".rbx": "ruby",
	".rbxs": "lua",
	".rd": "r",
	".rdf": "xml",
	".rdoc": "rdoc",
	".reb": "rebol",
	".rebol": "rebol",
	".red": "red",
	".reds": "red",
	".reek": "yaml",
	".rest": "restructuredtext",
	".rg": "rouge",
	".rhtml": "rhtml",
	".rkt": "racket",
	".rktd": "racket",
	".rktl": "racket",
	".rl": "ragel in ruby host",
	".rmd": "rmarkdown",
	".robot": "robotframework",
	".ron": "markdown",
	".rq": "sparql",
	".rs": "renderscript",
	".rsh": "renderscript",
	".rss": "xml",
	".rst": "restructuredtext",
	".rsx": "r",
	".ru": "ruby",
	".ruby": "ruby",
	".rviz": "yaml",
	".s": "gas",
	".sage": "sage",
	".sagews": "sage",
	".sas": "sas",
	".sass": "sass",
	".sats": "ats",
	".sbt": "scala",
	".sc": "scala",
	".scad": "openscad",
	".scala": "scala",
	".scaml": "scaml",
	".scd": "supercollider",
	".sce": "scilab",
	".sch": "eagle",
	".sci": "scilab",
	".scm": "scheme",
	".scpt": "applescript",
	".scrbl": "racket",
	".scss": "scss",
	".scxml": "xml",
	".self": "self",
	".sh": "shell",
	".sh-session": "shellsession",
	".shader": "glsl",
	".shen": "shen",
	".sig": "standard ml",
	".sj": "objective-j",
	".sjs": "javascript",
	".sl": "slash",
	".sld": "scheme",
	".slim": "slim",
	".sls": "saltstack",
	".sma": "sourcepawn",
	".sml": "standard ml",
	".sp": "sourcepawn",
	".sparql": "sparql",
	".spin": "propeller spin",
	".sps": "scheme",
	".sqf": "sqf",
	".sql": "plsql",
	".srdf": "xml",
	".ss": "scheme",
	".ssjs": "javascript",
	".st": "html",
	".stTheme": "xml",
	".sthlp": "stata",
	".ston": "ston",
	".storyboard": "xml",
	".sty": "tex",
	".styl": "stylus",
	".sublime-build": "javascript",
	".sublime-commands": "javascript",
	".sublime-completions": "javascript",
	".sublime-keymap": "javascript",
	".sublime-macro": "javascript",
	".sublime-menu": "javascript",
	".sublime-mousemap": "javascript",
	".sublime-project": "javascript",
	".sublime-settings": "javascript",
	".sublime-snippet": "xml",
	".sublime-theme": "javascript",
	".sublime-workspace": "javascript",
	".sublime_metrics": "javascript",
	".sublime_session": "javascript",
	".sv": "systemverilog",
	".svg": "svg",
	".svh": "systemverilog",
	".swift": "swift",
	".t": "perl",
	".tab": "sql",
	".tac": "python",
	".targets": "xml",
	".tcc": "c++",
	".tcl": "tcl",
	".tcsh": "tcsh",
	".tea": "tea",
	".tex": "tex",
	".textile": "textile",
	".thor": "ruby",
	".thrift": "thrift",
	".thy": "isabelle",
	".tm": "tcl",
	".tmCommand": "xml",
	".tmLanguage": "xml",
	".tmPreferences": "xml",
	".tmSnippet": "xml",
	".tmTheme": "xml",
	".tml": "xml",
	".tmux": "shell",
	".toc": "tex",
	".toml": "toml",
	".tool": "shell",
	".tpl": "smarty",
	".tpp": "c++",
	".ts": "typescript",
	".tst": "gap",
	".ttl": "turtle",
	".tu": "turing",
	".twig": "twig",
	".txl": "txl",
	".txt": "text",
	".uc": "unrealscript",
	".udf": "sql",
	".ui": "xml",
	".upc": "unified parallel c",
	".urdf": "xml",
	".v": "coq",
	".vala": "vala",
	".vapi": "vala",
	".vark": "gosu",
	".vb": "visual basic",
	".vba": "visual basic",
	".vbhtml": "visual basic",
	".vbproj": "xml",
	".vbs": "visual basic",
	".vcl": "vcl",
	".vcxproj": "xml",
	".veo": "verilog",
	".vert": "glsl",
	".vh": "systemverilog",
	".vhd": "vhdl",
	".vhdl": "vhdl",
	".vhf": "vhdl",
	".vhi": "vhdl",
	".vho": "vhdl",
	".vhs": "vhdl",
	".vht": "vhdl",
	".vhw": "vhdl",
	".vim": "viml",
	".viw": "sql",
	".volt": "volt",
	".vrx": "glsl",
	".vshader": "glsl",
	".vxml": "xml",
	".w": "c",
	".watchr": "ruby",
	".webidl": "webidl",
	".weechatlog": "irc log",
	".wisp": "wisp",
	".wl": "mathematica",
	".wlt": "mathematica",
	".wlua": "lua",
	".wsdl": "xml",
	".wsf": "xml",
	".wsgi": "python",
	".wxi": "xml",
	".wxl": "xml",
	".wxs": "xml",
	".x": "logos",
	".x3d": "xml",
	".xacro": "xml",
	".xaml": "xml",
	".xc": "xc",
	".xht": "html",
	".xhtml": "html",
	".xi": "logos",
	".xib": "xml",
	".xlf": "xml",
	".xliff": "xml",
	".xm": "logos",
	".xmi": "xml",
	".xml": "xml",
	".xml.dist": "xml",
	".xojo_code": "xojo",
	".xojo_menu": "xojo",
	".xojo_report": "xojo",
	".xojo_script": "xojo",
	".xojo_toolbar": "xojo",
	".xojo_window": "xojo",
	".xpl": "xproc",
	".xproc": "xproc",
	".xpy": "python",
	".xq": "xquery",
	".xql": "xquery",
	".xqm": "xquery",
	".xquery": "xquery",
	".xqy": "xquery",
	".xs": "xs",
	".xsd": "xml",
	".xsjs": "javascript",
	".xsjslib": "javascript",
	".xsl": "xslt",
	".xslt": "xslt",
	".xtend": "xtend",
	".xul": "xml",
	".y": "bison",
	".yaml": "yaml",
	".yml": "yaml",
	".zcml": "xml",
	".zep": "zephir",
	".zimpl": "zimpl",
	".zmpl": "zimpl",
	".zpl": "zimpl",
	".zsh": "shell",
	}
	  
	  